languages:
  Ruby: true
engines:
  duplication:
    enabled: true
      languages:
      - ruby
    exclude_paths:
    - "lib/inprovise/node.rb"
    - "lib/inprovise/control.rb"
  rubocop:
    enabled: true
    checks:
      Rubocop/Lint/RescueException:
        enabled: false
      Rubocop/Metrics/ClassLength:
        enabled: false
