engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_paths:
    - "lib/inprovise/node.rb"
    - "lib/inprovise/control.rb"
    - "lib/inprovise/cli/provision.rb"
    - "lib/inprovise/cli/node.rb"
    - "lib/inprovise/cli/group.rb"
    - "lib/inprovise/helper/linux.rb"
    - "lib/inprovise/channel/ssh.rb"
  rubocop:
    enabled: true
    checks:
      Rubocop/Lint/RescueException:
        enabled: false
      Rubocop/Metrics/ClassLength:
        enabled: false
ratings:
   paths:
   - "lib/**/*"
