before_install:
  - gem install bundler
bundler_args: "--verbose"
script: "rake test"
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4
  - ruby-head
gemfile:
  - Gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
env:
  CODECLIMATE_REPO_TOKEN=2b46019558c79326fc3cc87f2e4261610256aee236063c4b62b8ed8d2c2ce21d bundle exec rake
addons:
    code_climate:
        repo_token: 2b46019558c79326fc3cc87f2e4261610256aee236063c4b62b8ed8d2c2ce21d
